// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brzaxcbgydiipaszcadc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyemF4Y2JneWRpaXBhc3pjYWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzA1NDcsImV4cCI6MjA3NDMwNjU0N30.NyrU3Fo0k0wrCIApSy2MJdElXGt3bLSZIq5bH5pV-_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});